In [1]:
"""Special methods are meant to be called by the intepreter. You don't write my_object.__len__(). 
You write, len(my_object) then python calls the __len__ instance method"""

"Special methods are meant to be called by the intepreter. You don't write my_object.__len__(). \nYou write, len(my_object) then python calls the __len__ instance method"

In [2]:
"""Use len, iter, str built-functions instead"""

'Use len, iter, str built-functions instead'

In [17]:
from math import *

class Vector:
    
    def __init__(self, x=0, y=0):
        self.x = x
        self.y = y
        
    def __repr__(self):
        return 'Vector(%r, %r)' % (self.x, self.y)
    
    def __abs__(self):
        return hypot(self.x, self.y)
    
    def __bool__(self):
        return bool(abs(self))
    
    def __add__(self, other):
        x = self.x + other.x
        y = self.y + other.y
        return Vector(x,y)
    
    def __mul__(self, scaler):
        return Vector(self.x*scaler, self.y*scaler)
    


In [18]:
myvector = Vector(3,4)

In [19]:
myvector

Vector(3, 4)

In [20]:
myvector1 = Vector(6,4)

In [21]:
myvector1

Vector(6, 4)

In [14]:
myvector2 = myvector + myvector1

In [15]:
myvector2

Vector(9, 8)

In [22]:
bool(myvector2)

True

In [27]:
myvector * 3

Vector(9, 12)

In [24]:
myvector3

Vector(9, 8)

In [28]:
abs(myvector3)

12.041594578792296

In [29]:
"""CONTAINER SEQUENCES"""

'CONTAINER SEQUENCES'

In [30]:
"""list, tuple, and collections.deque can hold items of different types"""

'list, tuple, and collections.deque can hold items of different types'

In [31]:
"""FLAT SEQUENCES"""

'FLAT SEQUENCES'

In [32]:
""" str, bytes, bytearray, memoryview, and array.array hold items of one type"""

' str, bytes, bytearray, memoryview, and array.array hold items of one type'

In [33]:
"""MUTABLE SUQUENCES"""

'MUTABLE SUQUENCES'

In [34]:
"""list, bytearray, array.array, collections.deque and memoryview"""

'list, bytearray, array.array, collections.deque and memoryview'

In [35]:
"""IMMUTABLE SEQUENCES"""

'IMMUTABLE SEQUENCES'

In [36]:
""" tuple, str, and bytes"""

' tuple, str, and bytes'

In [37]:
symbols = '$&^#%'
codes = []
for symbol in symbols:
    codes.append(ord(symbol))

In [38]:
codes

[36, 38, 94, 35, 37]

In [39]:
listcodes = [ord(symbol) for symbol in symbols]

In [40]:
listcodes

[36, 38, 94, 35, 37]

In [41]:
"""List Comps do anything Map and filter do"""

'List Comps do anything Map and filter do'

In [42]:
"""Cartesian prosuct is  a list containing tuples built from all items from two or more lists"""

'Cartesian prosuct is  a list containing tuples built from all items from two or more lists'

In [43]:
colors = ['black', 'white']
sizes = ['S', 'M', 'L']
tshirts = [(color, size) for color in colors for size in sizes]

In [44]:
tshirts

[('black', 'S'),
 ('black', 'M'),
 ('black', 'L'),
 ('white', 'S'),
 ('white', 'M'),
 ('white', 'L')]

In [45]:
tbysizeshirts = [(color, size) for size in sizes for color in colors]

In [46]:
tbysizeshirts

[('black', 'S'),
 ('white', 'S'),
 ('black', 'M'),
 ('white', 'M'),
 ('black', 'L'),
 ('white', 'L')]

In [54]:
def my_function(x):
    y = x + 1
    x_sqrd = x+x
    return (x_sqrd, y)

In [55]:
five_plus = my_function(5)

In [56]:
five_plus

(10, 6)

In [57]:
print(five_plus)

(10, 6)


In [58]:
str(five_plus)

'(10, 6)'

In [59]:
print(repr(five_plus))

(10, 6)


In [60]:
"""ARRAY MATH"""

'ARRAY MATH'

In [65]:
import numpy as np

In [69]:
a1 = np.arange(10)

# a1

In [70]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [71]:
a1.shape

(10,)

In [74]:
list1 = [1,2,3,4,5,6,7]

In [75]:
r1 = np.array(list1)

In [76]:
r1

array([1, 2, 3, 4, 5, 6, 7])

In [82]:
print(r1>3) #Boolean indexing produces a list of boolean vlaues

[False False False  True  True  True  True]


In [81]:
print(r1[r1>3]) #You feed the list back into the array as the index to get the values associated

[4 5 6 7]


In [83]:
nums = np.arange(20)

In [84]:
nums

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [86]:
odd_nums = nums[nums % 2 == 1]
print(odd_nums)

[ 1  3  5  7  9 11 13 15 17 19]


In [87]:
even_nums = nums[nums % 2 == 0]
print(even_nums)

[ 0  2  4  6  8 10 12 14 16 18]


In [88]:
x1 = np.array([[1,2],[4,5]])
y1 = np.array([[7,8],[2,3]])

In [89]:
print(x1 * y1)

[[ 7 16]
 [ 8 15]]


In [91]:
"""DOT PRODUCT ALSO WORK ON RANK2 ARRAYS"""

'DOT PRODUCT ALSO WORK ON RANK2 ARRAYS'

In [94]:
x2 = np.array([[1,2,3],[4,5,6]])
y2 = np.array([[7,8],[9,10],[11,12]])
print(np.dot(x2,y2))

[[ 58  64]
 [139 154]]


In [95]:
"""Creating a Series using a Specified Index"""

'Creating a Series using a Specified Index'

In [97]:
import pandas as pd
series = pd.Series([1,2,3,4,5], index = ['a', 'b', 'c', 'd', 'c'])

In [98]:
print(series)

a    1
b    2
c    3
d    4
c    5
dtype: int64


In [99]:
print(series[2]) 

3


In [100]:
print(series.iloc[2]) #Based on position of the index

3


In [101]:
print(series['d']) #Based on the value of the index

4


In [102]:
print(series.loc['d']) #based on the label in the index

4


In [103]:
print(series[2:])

c    3
d    4
c    5
dtype: int64


In [104]:
print(series.iloc[2:])

c    3
d    4
c    5
dtype: int64


In [114]:
dates1 = pd.date_range('20190525', periods = 12, freq = 'M')
print(dates1)

DatetimeIndex(['2019-05-31', '2019-06-30', '2019-07-31', '2019-08-31',
               '2019-09-30', '2019-10-31', '2019-11-30', '2019-12-31',
               '2020-01-31', '2020-02-29', '2020-03-31', '2020-04-30'],
              dtype='datetime64[ns]', freq='M')


In [115]:
series = pd.Series([1,2,3,4,5,6,7,8,9,10,11,12])

In [116]:
series.index = dates1

In [117]:
print(series)

2019-05-31     1
2019-06-30     2
2019-07-31     3
2019-08-31     4
2019-09-30     5
2019-10-31     6
2019-11-30     7
2019-12-31     8
2020-01-31     9
2020-02-29    10
2020-03-31    11
2020-04-30    12
Freq: M, dtype: int64


In [120]:
dates2 = pd.date_range('20190525', periods = 12, freq = 'MS') #For beggining of month
print(dates2)

DatetimeIndex(['2019-06-01', '2019-07-01', '2019-08-01', '2019-09-01',
               '2019-10-01', '2019-11-01', '2019-12-01', '2020-01-01',
               '2020-02-01', '2020-03-01', '2020-04-01', '2020-05-01'],
              dtype='datetime64[ns]', freq='MS')


In [121]:
"""Calculating IRR """

'Calculating IRR '

In [122]:
cash_flow = np.array([-2., .5, .75, 1.35])
years = np.arange(4)

In [123]:
def npv(irr, cfs, yrs):  
    return np.sum(cfs / (1. + irr) ** yrs)

In [124]:
print(npv(irr=0.10, cfs=cash_flow, yrs=years))

0.08865514650638584


In [125]:
from scipy.optimize import fsolve
def irr(cfs, yrs, x0):
    return np.asscalar(fsolve(npv, x0=x0, args=(cfs, yrs)))